# Generated by Django 2.2.1 on 2020-04-16 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal',
            name='refer_to',
        ),
        migrations.AddField(
            model_name='referal',
            name='refer_used_by',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='fo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
