# Generated by Django 2.2.1 on 2020-04-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200416_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referal',
        ),
    ]
