# Generated by Django 2.2.1 on 2020-04-16 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='refer_by',
            field=models.OneToOneField(on_delete='CASCADE', related_name='result', to=settings.AUTH_USER_MODEL),
        ),
    ]
